/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screens;


import DB_Connection.DBConnection;
import assets.User;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ahmed
 */
public class Users_screen extends javax.swing.JFrame {

    /**
     * Creates new form Users_screen
     */
    public Users_screen() {
        initComponents();
        clear();
        selectedDev();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void clear(){
txtaccount.setText("");
txtpassword.setText("");
txttype.setText("");
txtuser.setText("");

}
    Connection conn=null;
Statement st=null;
ResultSet rs=null;
PreparedStatement prst=null;
    
     public void selectedDev(){
        try{
     conn= DBConnection.getInstance().getconnection();
      st=conn.createStatement();
      rs=st.executeQuery("select* from users");
     tbusers.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(SQLException e){
       e.printStackTrace();
       }
    }
    
User pr=new User();
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txttype = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnedite = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbusers = new javax.swing.JTable();
        txtpassword = new javax.swing.JTextField();
        txtaccount = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttype.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jPanel1.add(txttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 150, -1));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("الحساب");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 60, 20));

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("المستخدم");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 60, 20));

        txtuser.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 150, -1));

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("النوع");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 60, 20));

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("كلمة المرور");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 80, 30));

        btndelete.setBackground(java.awt.Color.red);
        btndelete.setFont(new java.awt.Font("Traditional Arabic", 1, 22)); // NOI18N
        btndelete.setText("حذف");
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        btnadd.setBackground(new java.awt.Color(0, 255, 255));
        btnadd.setFont(new java.awt.Font("Traditional Arabic", 1, 22)); // NOI18N
        btnadd.setText("اضافة ");
        btnadd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddMouseClicked(evt);
            }
        });
        jPanel1.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, -1, -1));

        btnedite.setBackground(new java.awt.Color(51, 51, 255));
        btnedite.setFont(new java.awt.Font("Traditional Arabic", 1, 22)); // NOI18N
        btnedite.setText("تعديل");
        btnedite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnediteMouseClicked(evt);
            }
        });
        jPanel1.add(btnedite, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        tbusers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbusers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbusersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbusers);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 820, 240));

        txtpassword.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jPanel1.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 150, -1));

        txtaccount.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jPanel1.add(txtaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 150, -1));

        btncancel.setBackground(new java.awt.Color(51, 255, 51));
        btncancel.setFont(new java.awt.Font("Traditional Arabic", 1, 22)); // NOI18N
        btncancel.setText("رجوع");
        btncancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelMouseClicked(evt);
            }
        });
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {                                       
        if(txtaccount.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "please enter the  user want deleted");
        }
        else{
            try{
                //                 Connection conn=new DBConnection().getconnection();
                //
                //                PreparedStatement delete=conn.prepareStatement("DELETE FROM product WHERE ID=?");
                //                delete.setInt(1,Integer.valueOf(txtid.getText()));
                //                delete.execute();
                //
                pr.setAccount_name(txtaccount.getText());
                pr.Delete();
                JOptionPane.showMessageDialog(this, "user successfully Deleted" );
                selectedDev();
                clear();
            }
            catch(Exception e){
                e.printStackTrace();
            }

        }
    }                                      

    private void btnaddMouseClicked(java.awt.event.MouseEvent evt) {                                    
        try{
        

           
            pr.setAccount_name(txtaccount.getText());
            pr.setPassword(txtpassword.getText());
            pr.setType(txttype.getText());
            pr.setUser_name(txtuser.getText());
            pr.Add();

            JOptionPane.showMessageDialog(this, "user successfully addsd" );
            // conn.close();
            selectedDev();
            clear();
        }

        //if(add()==true){
            //JOptionPane.showMessageDialog(this, "product successfully addsd" );
            // }}
    catch(Exception e){
        e.printStackTrace();
        }
    }                                   

    private void btnediteMouseClicked(java.awt.event.MouseEvent evt) {                                      
        if(txtaccount.getText().isEmpty() ||txtuser.getText().isEmpty() || txtpassword.getText().isEmpty() || txttype.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Information ");
        }else
        {
            try{
                

               pr.setAccount_name(txtaccount.getText());
            pr.setPassword(txtpassword.getText());
            pr.setType(txttype.getText());
            pr.setUser_name(txtuser.getText());
            
                pr.Edite();
                JOptionPane.showMessageDialog(this, "user UPDATED ");
                selectedDev();
                clear();
            }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    }                                     

    private void tbusersMouseClicked(java.awt.event.MouseEvent evt) {                                     
        DefaultTableModel model=(DefaultTableModel)tbusers.getModel();
        int myindex=tbusers.getSelectedRow();
        
        txtaccount.setText(model.getValueAt(myindex, 0).toString());
        txtpassword.setText(model.getValueAt(myindex, 1).toString());
        txttype.setText(model.getValueAt(myindex, 2).toString());
        txtuser.setText(model.getValueAt(myindex,3 ).toString());

    }                                    

    private void btncancelMouseClicked(java.awt.event.MouseEvent evt) {                                       
        this.setVisible(false);
        new Main_screen().setVisible(true);

    }                                      

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedite;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbusers;
    private javax.swing.JTextField txtaccount;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txttype;
    private javax.swing.JTextField txtuser;
    // End of variables declaration                   
}
